export BRANCH_KEY="key_test_iigOe5ilx8SnPzVoCz0DAnapyFddgSuI"
export MODE="development"
export BRANCHIO_API_ENDPOINT="https://api.branch.io/v1/url"
export SHARE_PREVIEW_URL="http://api.local/share/order-image-urls/"
export SEND_LINK_URL="https://apidev.photogurus.com/send-app-link/"
export ASSEST_URL="https://imgd.photogurus.com"
